apiVersion: v1
kind: Service
metadata: 
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: redis-10.5.3
    heritage: Helm
    release: cloudwu          
  name: cloudwu-redis-master-new
  namespace: wucloud-test
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: <YOUR APP NAME>
    release: <YOUR RELEASE NAME>
    role: <YOUR ROLE NAME>
  sessionAffinity: None
  type: ClusterIP
