apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cloudwu
    meta.helm.sh/release-namespace: isd-cloudwu 
  labels:
    app: redis
    app.kubernetes.io/managed-by: Helm
    chart: redis-10.5.3
    heritage: Helm
    release: cloudwu          
  name: cloudwu-redis-master-new
  namespace: <namespace>
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis-new
    release: cloudwu
    role: master-new
  sessionAffinity: None
  type: ClusterIP
